### ISSUE TITLE
Feat - 회원 가입 기능

### ISSUE THREAD

**Issue by codesejin** [f-lab-edu/off-coupon#1]
# TodoList

- [x] 회원가입 관련 패키지 생성
   - 디렉토리 구조는 어떻게 가져가야 좋을까?
- [x]  DB 연결 및 관련 엔티티 설정
   - Mybatis Config 설정
- [x] 테스트 코드 작성
   - [x]  슬라이스 테스트 작성 
      - [x] Jacoco 설정
       - [x] Controller MockMvc
       - [x] Service
       - [x]  Repository
- [x]  회원 가입 시 받을 유저 정보
  - 이메일, 비밀번호(hashed), 이름, 생년월일, 휴대폰번호
- [x] 회원가입 관련 유효성 검증
   - [x]  포맷 검증
        - [x] 이메일 검증   
        - [x] 비밀번호 영단어 소문자, 숫자 1개 각각 이상씩 포함했는지 검증
        - [x] 핸드폰 번호 000-000-0000 혹은 000-0000-0000 검증
        - [x] 생년월일 YYYY-MM-DD 검증
   - [x] 이메일 중복 체크
   - [x] 비밀번호 8~13 자리 길이 검증
- [x] 유효성 검증 후 등록 시 확인해야할 점
   - [x] 비밀번호 암호화 설정 (`security.crypto.bcrypt.BCrypt` 사용)
   ---
   
   # ERD 다이어그램
   
<img width="912" alt="image" src="https://github.com/f-lab-edu/off-coupon/assets/101460733/135b7584-3b55-4e24-8f93-0dbe76d48431">

**Comment by f-lab-maverick** [comment]
회원가입시 저장할 데이터는 민감한 정보, 개인정보가 있어서 주의하여 설계해야 합니다. 아래 사항을 참고하여 ERD 구성을 진행해주세요~

1. 회원가입시 받을 개인정보의 범위를 지정해야 합니다.
2. 비밀번호 로그인 방식으로 인증을 진행할 경우 비밀번호를 어떻게 암호화하여 저장할지 고려해야 합니다.
2-1. 단순한 SHA-256과 같은 단방향 해시 암호화는 Rainbow table 공격에 취약합니다.
2-2. 이 부분은 소금이랑 후추를 좀 뿌려주면 됩니다. salt, pepper 기법이 있으니 찾아보시죠

**Comment by codesejin** [comment]
넵 찾아보겠습니다!

**Comment by codesejin** [comment]
@f-lab-maverick 

알려주신 내용 관련해서 3가지 테스트 해봤습니다.

1. `security.crypto.bcrypt.BCryptPasswordEncoder` 
2. `security.crypto.bcrypt.BCrypt`
3. `mindrot.jbcrypt.BCrypt`


<img width="711" alt="image" src="https://github.com/f-lab-edu/off-coupon/assets/101460733/1720e220-0534-4870-862c-fca472d3450a">

1번은 encode()메소드에서  BCrypt.gensalt() 를 이용해서 salt기법을 설정해주긴하지만, pepper를 적용할 수 없습니다.
그래서 2번과 3번 중에 결정하겠습니다!

**Comment by yyy9942** [comment]
Salt정도만 적용해주셔도 레인보우테이블 공격이 어느정도 방지되니 이정도만 적용해두셔도 됩니다. 구현 진행해주세요~

**Comment by f-lab-maverick** [comment]
Salt만 적용해주셔도 레인보우테이블 공격이 어느정도 방지됩니다. 구현 진행해주세요~
