### ISSUE TITLE
Feat - 테스트코드 추가

### ISSUE THREAD

**Issue by codesejin** [f-lab-edu/off-coupon#19]
- 기존 87개에서 `205개`까지 테스트 코드 추가

<img width="723" alt="image" src="https://github.com/f-lab-edu/off-coupon/assets/101460733/cf11fe5c-c19a-4d68-8158-e5218defc277">

# 테스트 전략

![image](https://github.com/f-lab-edu/off-coupon/assets/101460733/3d044be3-0f83-408f-9ae7-0ea52d805e46)

기존에 작성된 테스트의 경우 통합테스트, 인수테스트의 비중이 높았습니다.
일반적으로 테스트 코드는 위와 같은 피라미드 형식으로, 단위 테스트의 비중이 더 높아야 합니다.
이번 Feature 에서는 단위테스트의 비중을 높이고, 집중적으로 구현하고자했습니다.

# 단위테스트
```java
    @Nested
    @DisplayName("availableIssuePeriodAndTime - 이벤트 기간 검증")
    class availableIssuePeriodAndTimeMethodForEventPeriod {
        LocalDateTime validNow =  LocalDateTime.of(2024, 02, 01, 13, 00, 00);

        @DisplayName("[ERROR] 요청 값이 이벤트 기간 범위가 아닌 경우 EventPeriodException 발생")
        @ParameterizedTest(name = "[{index}] {1}")
        @CsvSource({
                "2024-01-01T13:00:00, 요청 값이 이벤트 기간 범위보다 이전 일 경우",
                "2024-03-01T13:00:00, 요청 값이 이벤트 기간 범위보다 이후 일 경우"
        })
        void availableIssuePeriodAndTime_with_fail_invalid_request_date(String requestDateString, String caseDescription) {
            LocalDateTime requestDate = LocalDateTime.parse(requestDateString);

            eventRedisEntity = new EventRedisEntity(1L, "category", "description",
                    startDate, endDate, dailyIssueStartTime, dailyIssueEndTime);

            EventPeriodException exception = assertThrows(EventPeriodException.class, () -> eventRedisEntity.availableIssuePeriodAndTime(requestDate));

            assertNotNull(exception);
            assertEquals(INVALID_EVENT_PERIOD.formatted(startDate, endDate), exception.getMessage());
        }
        @DisplayName("[ERROR] 설정된 이벤트 기간이 null 경우 EventPeriodException 발생 ")
        @Test
        void availableIssuePeriodAndTime_fail_with_null() {
            eventRedisEntity = new EventRedisEntity(1L, "category", "description",
                    null, null, "00:00:00", "23:59:59");

            EventPeriodException exception = assertThrows(EventPeriodException.class, () -> eventRedisEntity.availableIssuePeriodAndTime(validNow));
            assertNotNull(exception);
            assertEquals(EVENT_PERIOD_IS_NULL.formatted(null, null), exception.getMessage());
        }

        @DisplayName("[SUCCESS] 요청 값이 이벤트 기간 범위인 경우 ")
        @Test
        void availableIssuePeriodAndTime_success() {
            eventRedisEntity = new EventRedisEntity(1L, "category", "description",
                    startDate, endDate, dailyIssueStartTime, dailyIssueEndTime);
            assertDoesNotThrow(() -> eventRedisEntity.availableIssuePeriodAndTime(validNow));
        }
    }
```
![image](https://github.com/f-lab-edu/off-coupon/assets/101460733/fc4254a7-e279-4af2-a59b-a990669e0cc6)

# 테스트코드 작성 시 어려운 점

1. 내부 로직을 모르는 상태로 단위 테스트를 작성해야 하는데, 도메인 객체 내부에 있는 로직이 복잡할 경우 테스트 코드 작성을 어떻게 해야 할지 애매합니다.
- ex. 메소드 내부적으로 조건문 혹은  계산 로직이 있을 경우, 테스트코드내에서도 동일한 로직을 사용하기 때문에 좋지 않다고 생각했습니다.

2. 비동기 API의 경우 스케줄링과 함께 돌아가는데, 멱등성 보장이 되지 않습니다
- 통합테스트 중 데이터가 대기 큐에 담긴 후에 스케줄링을 통해 DB에 저장되기 때문에  delete가 어렵다고 생각했습니다.
- awaitility 라이브러리와 함께 사용해서 대기하도록 설정하긴했지만, 아직 완전하지 않습니다.

3. Stub코드를 사용해서 의존성을 분리해보려고 시도했지만, 의존성이 많아서 테스트를 위한 추가 코드가 많아지고 확실하게 모르겠습니다.
- ex. Cacheable 어노테이션이 붙은 경우 redis를 Mock로써 어떻게 표현해야할지?

4. 객체 래핑하는 방식으로 하다보니 getter 사용이 많아지는데, 이 방식이면 클래스간의 결합도가 높아지는게 아닌지 궁금합니다.

**Comment by f-lab-maverick** [comment]
**내부 로직을 모르는 상태로 단위 테스트를 작성해야 하는데, 도메인 객체 내부에 있는 로직이 복잡할 경우 테스트 코드 작성을 어떻게 해야 할지 애매합니다.**
-> 왜 몰라야한다고 생각하시나요? 테스트는 해당 해위가 어떤 영향을 발생시키고, 어떤 결과가 나오는지 알아야 작성할 수 있습니다. 나쁜 테스트는 내부 '로직'이 아니라 내부 '구현'에 의존하는 테스트입니다. 구현을 조금만 변경해도 깨져버리는 테스트가 있는데, 이런 테스트로만 만들지 않으면 됩니다.

**비동기 API의 경우 스케줄링과 함께 돌아가는데, 멱등성 보장이 되지 않습니다
통합테스트 중 데이터가 대기 큐에 담긴 후에 스케줄링을 통해 DB에 저장되기 때문에 delete가 어렵다고 생각했습니다.
awaitility 라이브러리와 함께 사용해서 대기하도록 설정하긴했지만, 아직 완전하지 않습니다.**
-> 테스트의 단위를 쪼개주시면 됩니다. 
- 1. 쿠폰 요청을 하면 대기 큐에 담긴다
- 2. 대기큐에 담긴 요청은 스케줄링을 통해 DB에 저장된다
각각 별개의 테스트로 돌리면 됩니다. delete가 되지 않는것은 큰 이슈가 없습니다. 테스트마다 고정된 id가 아닌 신규 id를 사용한다면 겹치는 쿠폰이 없어서 문제 없지 않을까요?

**Stub코드를 사용해서 의존성을 분리해보려고 시도했지만, 의존성이 많아서 테스트를 위한 추가 코드가 많아지고 확실하게 모르겠습니다.
ex. Cacheable 어노테이션이 붙은 경우 redis를 Mock로써 어떻게 표현해야할지?
객체 래핑하는 방식으로 하다보니 getter 사용이 많아지는데, 이 방식이면 클래스간의 결합도가 높아지는게 아닌지 궁금합니다.**
-> 테스트의 목적과 대상을 다시 떠올려보세요. `@Cacheable`이 동작하는지를 mock 단위테스트코드로 표현하는게 적절할까요? 저 기능은 Spring cache 프로젝트의 기능이고, 이 프로젝트의 기능이 동작하는지를 테스트하는것은 마지 JVM이 정상동작하는지 테스트하는것과 마찬가지인 불필요한 행위가 될 수 있습니다.
