### ISSUE TITLE
Feat - 로그인 기능 구현

### ISSUE THREAD

**Issue by codesejin** [f-lab-edu/off-coupon#3]
# 로그인 기능 구현
  - [x] spring security form login
- [x] session ID 저장
  - [x] Redis Session storage 적용

---
# 세션 vs 토큰 중 세션 선택

1. `토큰`은 세션보다 `크기가 커서` 대역폭 소비가 증가해서 `트래픽이 많은 사이트에서는 로드 시간에 영향을 끼칩니다`
2. `토큰`의 사용 핵심이 `stateless`하다는 점인데, refresh토큰이나 blacklist/whitelist를 사용할 경우 `DB에 접근`하는게 session과 다를바가 없습니다  
3. `토큰`을 사용할 경우 `복호화하는 과정에서 오버헤드가 발생`해서 세션보다 느립니다.  

#  session 선택 시 다중화 할 경우 Redis의 session storage 선택

1. `stickey session`은 다중화할 경우 요청이 처음 연결되었던 서버로만 가게끔 하는 건데, 이러면 분산처리의 의미가 없어지고 트래픽 병목 현상이 발생할 가능성이 있습니다
2. `session clustering`은 모든 서버에 session을 복제해야한다는 점에서 메모리 사용량이 높아지고, 특정 서버의 key만 복사할 경우에 primary서버에서 값을 읽어와야 하기 때문에 오버헤드가 발생합니다.

**Comment by f-lab-maverick** [comment]
@codesejin stickey session은 모든 요청이 첫 서버로만 가게 만드는 의미가 아닙니다. 세션이 처음 연결되었던 서버로 계속해서 연결될 수 있게 로드밸런싱을 해준다는 뜻이라서, 의미를 다시 찾아보시는게 좋을 것으로 보입니다.

**Comment by codesejin** [comment]
넵 설명을 제대로 못한것 같습니다! 수정했습니다!
